server.port=8081

# Redis
spring.data.redis.host=localhost
spring.data.redis.port=6379

# JWT - same approach as notification service
jwt.secret=mySecretKeyForRateLimiterChangeThisInProd
jwt.expiration.ms=86400000

# Rate limit config - keeping these in properties so they're easy to change
# without touching code
rate.limit.token-bucket.capacity=10
rate.limit.token-bucket.refill-per-minute=10
rate.limit.sliding-window.max-requests=20
rate.limit.sliding-window.window-seconds=60

logging.level.com.ram=DEBUG
